### ISSUE TITLE
Additional Settings Documentation Required for Running on Windows

### ISSUE THREAD

**Issue by kevinrhaas** [dekarlab/pentahor#1]
My environment may be unique, but i had to add the path on my system variables for R.dll to my PATH variable, for example: C:\R\R-3.0.2\bin\x64

Also, this is fairly obvious, but you may want to clarify explanation for Windows on step 4 to say (for 64-bit)
Copy %R_HOME%\library\rJava\jri\x64 to pdi-ee\data-integration\libswt\win64

**Comment by dekarlab** [comment]
Kevin, 
thank you for suggestions. I have corrected the installation instructions. 
Denis
