### ISSUE TITLE
Problem of reading

### ISSUE THREAD

**Issue by anaisf66** [dekarlab/pentahor#13]
Hi,
I'm trying to get the plugin into Pentaho and I tried to do exactly what you said but I've a problem : I find the plugin into Scripting (not statistics), and I have this problem: java.lang.UnsatisfiedLinkError: C:\Pentaho\data-integration\libswt\win64\jri.dll: Can't load IA 32-bit .dll on a AMD 64-bit platform.
Can you help me please?

**Comment by dekarlab** [comment]
There are two different jri libraries. One 32 bit and one 64 bit. You should copy 64 bit library from jri (c:\Program Files\R\R-3.1.2\library\rJava\jri\x64\jri.dll) to 
 C:\Pentaho\data-integration\libswt\win64.
