### ISSUE TITLE
Using JRE 7 and PDI 5.0.1 CE

### ISSUE THREAD

**Issue by davidfombella** [dekarlab/pentahor#2]
Found this JRI issue
2014/03/13 13:01:03 - Execute R Script.0 - ERROR (version 5.0.1-stable, build 1 from 2013-11-15_16-08-58 by buildguy) : Unexpected error
2014/03/13 13:01:03 - Execute R Script.0 - ERROR (version 5.0.1-stable, build 1 from 2013-11-15_16-08-58 by buildguy) : java.lang.UnsatisfiedLinkError: no jri in java.library.path
2014/03/13 13:01:03 - Execute R Script.0 -  at java.lang.ClassLoader.loadLibrary(Unknown Source)
2014/03/13 13:01:03 - Execute R Script.0 -  at java.lang.Runtime.loadLibrary0(Unknown Source)
2014/03/13 13:01:03 - Execute R Script.0 -  at java.lang.System.loadLibrary(Unknown Source)
2014/03/13 13:01:03 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.loadJRILibrary(PRCalc.java:178)
2014/03/13 13:01:03 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.processRow(PRCalc.java:193)
2014/03/13 13:01:03 - Execute R Script.0 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:60)
2014/03/13 13:01:03 - Execute R Script.0 -  at java.lang.Thread.run(Unknown Source)

**Comment by dekarlab** [comment]
Hi,

This error is occurred, since plugin can not find the needed library for JRI (java interface in R). It is needed to copy jri.dll from JRI folder to folder specified in step 2, when you press Help Button direct from plugin. (http://dekarlab.de/img/execute_r_script_help.jpg)
