### ISSUE TITLE
Issue in setting up plugin in PDI 4.4 CE

### ISSUE THREAD

**Issue by nkap00r** [dekarlab/pentahor#3]
Hi,

Very pleased to see this initiative - Great job!!

I tried setting up the plugin in PDI 4.4 CE running on Windows 7 - 32 bit OS.
(I followed the instructions as provided at http://dekarlab.de/wp/?p=5)

I could see the 'Execute R Script' step under Scripting in Spoon however i get error when creating step. Attached below is the screen i get

![rscripterror](https://f.cloud.github.com/assets/5593923/2498233/a6827206-b343-11e3-80e5-25f13124255c.PNG)

Would be very keen to see it working and would appreciate any help in moving forward with this.

Thanks & Regards,
Nikhil

**Comment by dekarlab** [comment]
Hi Nikhil,

I've compiled the plugin using java 7, therefore the old java version are not supported. You need to update the java (jdk) to new version or recompile plugin from source.

Denis

**Comment by nkap00r** [comment]
Hi Denis.

Many thanks. It has worked.

Regards,
Nikhil
