### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by joyofdata** [dekarlab/pentahor#4]
Hi!

Is the missing of a license by intention? 

I am asking because this implies the usual strict copyright regulations and by that legally prohibits forking the code. 

It also makes using the plugin especially for professional purposes legally problematic. 

The plug-in is pretty awesome and it would be a shame to handicap its utilization and development by keeping its licensing in limbo.

MIT license might be good choice: http://en.wikipedia.org/wiki/MIT_License

Kind regards

Raffael

**Comment by dekarlab** [comment]
The license is GPL.
