### ISSUE TITLE
Error Installing RScript Plugin in Spoon 5.1

### ISSUE THREAD

**Issue by dominikschopper** [dekarlab/pentahor#5]
We have e problem installing the RScrip Plugin under Windows. If I follow the instructions (R is installed and functioning, Environment Vars are set), I ge the error: pentaho de/dekarlab/pentahor/plugin/PRCalcMeta : Unsupported major.minor version 51.0
Is there a fix for his?

**Comment by dekarlab** [comment]
Hi Dominik,

You use old java version, I have compiled the code using jdk 7.0. There are two options:
- update java
  or
- recompile the project from sources using your java version

Best wishes,
Denis
