### ISSUE TITLE
Error by executing R script: null 2014/12/12 16:52:50 - Execute R Script.0 -  at java.lang.Thread.run (Thread.java:745)

### ISSUE THREAD

**Issue by FCIOmar** [dekarlab/pentahor#7]
i installed R 3.1.2 with PDI 5.2 CE and 

 i try all R Script Plugin 1,2,3 even you new one that solve null pointer exception but this error still exist
what is the wrong with this

**Comment by dekarlab** [comment]
Hi,

Can you please sen me a screenshot of transformation? And additional log messages?

Thanks,
Denis

**Comment by FCIOmar** [comment]
Hi
thanks for reply i try to change java version to 7 the past error dissapear instead this  
 the kettle  was crash after Running transformation without erorr
 i try to run transformation from pan.bat instead of GUI and this was result
the last line was "RshowMessage"
![kettle](https://cloud.githubusercontent.com/assets/10159871/5427782/f953b188-83b4-11e4-9724-08946f504631.PNG)
![log11](https://cloud.githubusercontent.com/assets/10159871/5427783/f95a1b54-83b4-11e4-8c28-16d7e6c611a8.PNG)
![log22](https://cloud.githubusercontent.com/assets/10159871/5427784/f95ec01e-83b4-11e4-97a5-217a5248a76e.PNG)

**Comment by EngEmanAli25** [comment]
I have same problem

**Comment by FCIOmar** [comment]
Any Answers??

**Comment by dekarlab** [comment]
The plugin is worked with R version 3.0.1, but it does not work with R version 3.1.2. I will check this.

**Comment by joyofdata** [comment]
Hey Mr. dekarlab, thanks for your effort! Best Wishes and Merry Christmas!

**Comment by FCIOmar** [comment]
Thanks for the Rsponce
I also try this 3.0.1 but the same error appear what about Kettle Version u test on it
Thanks

**Comment by dekarlab** [comment]
Have you copied the jri.dll from version 3.0.1 and updated the paths to this version? I use Kettle 5.2.

**Comment by FCIOmar** [comment]
yes i copy jri from  rjava/rJava_0.9-6\rJava\jri\x64
and adding this to my path 
i follow your tutorial as it is

**Comment by dekarlab** [comment]
Hi,

I have found the problem. The R_HOME should be specified as a root to R:
R_HOME=C:\Program Files\R\R-3.1.2
but NOT as 
R_HOME=C:\Program Files\R\R-3.1.2*bin\x64*

**Comment by FCIOmar** [comment]
thanks for reply
this really solve the problem of crashing but return me to the first error again
i try to install plugin from marketplace once and 
try download and install plugine manullay as another try 
but the same error appear![log1](https://cloud.githubusercontent.com/assets/10159871/5574283/727ec33a-8fc3-11e4-815c-184db597ffcb.PNG)
![log2](https://cloud.githubusercontent.com/assets/10159871/5574282/726d35ca-8fc3-11e4-8618-1ede3cd8d5f5.PNG)

**Comment by dekarlab** [comment]
You can try to remove lazy flag in your first step.

**Comment by FCIOmar** [comment]
OH oh
thanks very much
 finally i can run it without errors and return output

**Comment by dekarlab** [comment]
this is good:)
