### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jri in java.library.path error

### ISSUE THREAD

**Issue by adeydas** [dekarlab/pentahor#8]
Hi,

I am trying to run the step on a Windows x64 machine. I have copied the JRI jars to libswt and set R_HOME. But I still keep on getting this error:

java.lang.UnsatisfiedLinkError: no jri in java.library.path

Here's the stack trace from Kettle:

2015/01/21 14:58:51 - Execute R Script.0 - Loading JRI library from: C:\Users\Abhishek\IdeaProjects\kettle\libswt\win64
2015/01/21 14:58:51 - Execute R Script.0 - R is installed in R_HOME: C:\Program Files\R\R-3.1.2
2015/01/21 14:58:51 - Execute R Script.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2015-01-06 10.04.19 by abhishek) : Unexpected error
2015/01/21 14:58:51 - Execute R Script.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2015-01-06 10.04.19 by abhishek) : java.lang.UnsatisfiedLinkError: no jri in java.library.path
2015/01/21 14:58:51 - Execute R Script.0 -  at java.lang.ClassLoader.loadLibrary(Unknown Source)
2015/01/21 14:58:51 - Execute R Script.0 -  at java.lang.Runtime.loadLibrary0(Unknown Source)
2015/01/21 14:58:51 - Execute R Script.0 -  at java.lang.System.loadLibrary(Unknown Source)
2015/01/21 14:58:51 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.loadJRILibrary(PRCalc.java:182)
2015/01/21 14:58:51 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.processRow(PRCalc.java:197)
2015/01/21 14:58:51 - Execute R Script.0 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/01/21 14:58:51 - Execute R Script.0 -  at java.lang.Thread.run(Unknown Source)

Please help. Thanks.

**Comment by dekarlab** [comment]
Hi,

Can you try to copy jri.dll to: C:\Users\Abhishek\IdeaProjects\kettle\libswt\win64?

**Comment by adeydas** [comment]
Thanks that worked but now I have a new error. I am trying out a simple sum script and I get the following error:

2015/01/23 11:44:33 - Execute R Script.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2015-01-06 10.04.19 by abhishek) : Unexpected error
2015/01/23 11:44:33 - Execute R Script.0 - ERROR (version TRUNK-SNAPSHOT, build 1 from 2015-01-06 10.04.19 by abhishek) : org.pentaho.di.core.exception.KettleException: 
2015/01/23 11:44:33 - Execute R Script.0 - Error by executing R script: [[B@648a17a4, [B@6a4df545, null, null, null, null, null, null, null, null, null, null]
2015/01/23 11:44:33 - Execute R Script.0 - [B cannot be cast to java.lang.Double
2015/01/23 11:44:33 - Execute R Script.0 - 
2015/01/23 11:44:33 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.processRow(PRCalc.java:251)
2015/01/23 11:44:33 - Execute R Script.0 -  at org.pentaho.di.trans.step.RunThread.run(RunThread.java:62)
2015/01/23 11:44:33 - Execute R Script.0 -  at java.lang.Thread.run(Unknown Source)
2015/01/23 11:44:33 - Execute R Script.0 - Caused by: java.lang.ClassCastException: [B cannot be cast to java.lang.Double
2015/01/23 11:44:33 - Execute R Script.0 -  at de.dekarlab.pentahor.RRunner.initVariable(RRunner.java:195)
2015/01/23 11:44:33 - Execute R Script.0 -  at de.dekarlab.pentahor.RRunner.initVariables(RRunner.java:183)
2015/01/23 11:44:33 - Execute R Script.0 -  at de.dekarlab.pentahor.RRunner.run(RRunner.java:131)
2015/01/23 11:44:33 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.runR(PRCalc.java:84)
2015/01/23 11:44:33 - Execute R Script.0 -  at de.dekarlab.pentahor.plugin.PRCalc.processRow(PRCalc.java:239)
2015/01/23 11:44:33 - Execute R Script.0 -  ... 2 more

**Comment by dekarlab** [comment]
You can try to remove lazy flag in your first step, where you read data from csv.

**Comment by adeydas** [comment]
Tried that but didn't work.

**Comment by dekarlab** [comment]
You can also try this example:
http://dekarlab.de/download/pentahor_test.zip

**Comment by omejiasq** [comment]
Hi. I im trying to exexute the example pentahor_test.zip in PDI 5.4, as R 3.3.1, and i copy jri.dll to data-integration\libswt\win64 folder in windows 10, but i get this error:  ERROR (version 5.4.0.1-130, build 1 from 2015-06-14_12-34-55 by buildguy) : java.lang.UnsatisfiedLinkError: C:\pentaho\data-integration\libswt\win64\jri.dll: Can't find dependent libraries. How i can to fix this error please?

**Comment by rmargerum** [comment]
me too.... @omejiasq

**Comment by yandro-dev** [comment]
Hiiiiiiii I have the same problem!!!! I im trying to exexute the example pentahor_test.zip in PDI 5.0.1, as R 3.6.3, and i copy jri.dll to data-integration\libswt\win64 folder in windows 10, but i get this error:- ERROR (version 5.0.1-stable, build 1 from 2013-11-15_16-08-58 by buildguy) : java.lang.UnsatisfiedLinkError: C:\Users\YANDRO\Desktop\data-integration\libswt\win64\jri.dll: Can't find dependent libraries. How i can to fix this error please?
