### ISSUE TITLE
 R scripts error

### ISSUE THREAD

**Issue by Longtailneighbor** [dekarlab/pentahor#9]
Hi , beg for your some time
i am trying to use R script with pentaho,but it always get in trouble just like next,can you help me?

2015/04/05 14:09:02 - Execute R Script.0 - ERROR (version 5.2.0.0, build 1 from 2014-09-30_19-48-28 by buildguy) : org.pentaho.di.core.exception.KettleException: 
2015/04/05 14:09:02 - Execute R Script.0 - Error by executing R script: null
2015/04/05 14:09:02 - Execute R Script.0 -  at java.lang.Thread.run (Thread.java:745)

i get another anwser on"https://github.com/dekarlab/pentahor/issues/7",and try,but not work

**Comment by dekarlab** [comment]
Hi,

Can you please run the example http://dekarlab.de/download/pentahor_test.zip to check if the same erorr occured?

**Comment by sbecainfo** [comment]
Hi. That example works for me. I'm running this on Pentaho 5.3 CE.
But still no luck with scripts that span multiple lines..

On Mon, Apr 13, 2015 at 2:54 PM, DEKAR laboratory notifications@github.com
wrote:

> Hi,
> 
> Can you please run the example
> http://dekarlab.de/download/pentahor_test.zip to chack if the same erorr
> occured?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dekarlab/pentahor/issues/9#issuecomment-92511785.

## 

_Sebastian Beca_ _| Sr Data Engineer_
sebastian@infoscout.co\*  | +1 415.624.6149*

[image: infoscout.co] http://www.infoscout.co/

**Comment by dekarlab** [comment]
I think you have the same issue as it was by me. If the r file is very complex, than it is difficult to evaluate  it with jri. In this case there is a work around: define functions. For example, on the page http://dekarlab.de/wp/?p=5 below:
/code/r/Run.R - simple script, for referencing in pentaho, which calls complex script:
/code/r/func/MainScript.R

If you send me a screen shots of your transformation with error, than I can check it.

**Comment by sbecainfo** [comment]
Your right! I actually just used source("myscript.R") and called the
function in that file and it worked!
I was resorting to putting everything in a shell step but this is much
better as I can bring data in and out without file exchange.
Thanks for the heads up on the docs!
Did you get yours running well and all?

On Mon, Apr 13, 2015 at 3:36 PM, DEKAR laboratory notifications@github.com
wrote:

> I think you have the same issue as it was by me. If the r file is very
> complex, than it is difficult to evaluate it with jri. In this case there
> is a work around: define functions. For example, on the page
> http://dekarlab.de/wp/?p=5 below:
> /code/r/Run.R - simple script, for referencing in pentaho, which calls
> complex script:
> /code/r/func/MainScript.R
> 
> If you send me a screen shots of your transformation with error, than I
> can check it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dekarlab/pentahor/issues/9#issuecomment-92519470.

## 

_Sebastian Beca_ _| Sr Data Engineer_
sebastian@infoscout.co\*  | +1 415.624.6149*

[image: infoscout.co] http://www.infoscout.co/

**Comment by dekarlab** [comment]
Super! 

I have used this plugin for cross validation of different models. It is good for that. The main functionality and data transfer were implemented using R. In pentaho I have defined only simple attributes, like period or values for parameters. The large data transfer between pentaho and R was not perfomant.

**Comment by sbecainfo** [comment]
Thats also good to know. I need to process data in R and the upload to
Vertica. Perhaps the best way to go is write to File and then use Pentaho's
Bulk Loader (COPY).
Thanks!
Sebastian

On Mon, Apr 13, 2015 at 4:24 PM, DEKAR laboratory notifications@github.com
wrote:

> Super!
> 
> I have used this plugin for cross validation of different models. It is
> good for that. The main functionality and data transfer were implemented
> using R. In pentaho I have defined only simple attributes, like period or
> values for parameters. The large data transfer between pentaho and R was
> not perfomant.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dekarlab/pentahor/issues/9#issuecomment-92532081.

## 

_Sebastian Beca_ _| Sr Data Engineer_
sebastian@infoscout.co\*  | +1 415.624.6149*

[image: infoscout.co] http://www.infoscout.co/

**Comment by waynefoltaERI** [comment]
**sbecaininfo's** solution of `source("myscript.R")` works. The issue is that this plugin feeds a single line at a time to R, via JRI, and if you have things like function definitions that are more than one line long, this breaks things. The plugin does not check the return value of the JRI `eval` call, so you don't know what's going wrong.

It does log whatever R prints out at that point -- so might display an error message if R generated one -- but the problem is that in this case R doesn't complain. I'm not sure if the `eval` return would be NULL to indicate there was an error, but that's what the documentation says.
